POST toastApp.ru/sign-in
Content-Type: application/json
{
  "email":"qooqay@blin.com",
  "password":"123123"
}

###

POST http://localhost:8080/sign-up
Content-Type: application/json
{
    "name":"Олег",
    "email":"123@123",
    "password":"123123"
}

###

GET http://localhost:8080/event
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6IjEyM0AxMjMiLCJwYXNzd29yZCI6IiQyYSQxMCRZQ25kQ3ZQTGtMVDhLenpZWGQ4cE1PbzZBT2g0ZlRpSjVySUUwUVJsTlFGVVN4U0tJczczMiJ9.sRPwrB7xU36fo49a0WZjB1l52fTfO3fLVOC0f8jd2Z6z2ofGKsnJQUKkBvbvGTNc5d-8BaG1ZZeSccyKN9kPMw

###

POST http://localhost:8080/event
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6IjEyM0AxMjMiLCJwYXNzd29yZCI6IiQyYSQxMCRZQ25kQ3ZQTGtMVDhLenpZWGQ4cE1PbzZBT2g0ZlRpSjVySUUwUVJsTlFGVVN4U0tJczczMiJ9.sRPwrB7xU36fo49a0WZjB1l52fTfO3fLVOC0f8jd2Z6z2ofGKsnJQUKkBvbvGTNc5d-8BaG1ZZeSccyKN9kPMw
Content-Type: application/json
{
  "name":"NewEventa",
  "description":"dadaafsff23",
  "date":"2021-05-23",
  "categoryId":2
}



